services:

  api:
    container_name: api-express
    build: ./projetoExpress
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./projetoExpress/.env

  spa:
    container_name: spa-wallet
    build: ./my-app
    depends_on:
      - api
    volumes:
      - spa-volume:/var/www/html

  nginx:
    container_name: nginx-wallet
    build: ./nginix
    ports:
      - 88:88
    volumes:
      - spa-volume:/var/www/html
    depends_on:
      - api
      - spa

volumes:
  spa-volume: